# GŁÓWNY FORMAT
format = "$username$hostname $directory$git_branch$git_status$cmd_duration$line_break$character"

# PRAWY PROMPT (Godzina)
right_format = "$time"

[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold yellow"
format = "@[$hostname]($style)"

[directory]
style = "bold purple"
truncation_length = 10
truncate_to_repo = false
format = " [$path]($style) "

[git_branch]
symbol = " "
style = "bold green"
format = " on $symbol$branch "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'bold red'
conflicted = '═'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead}⇣${behind}'
behind = '⇣${count}'
up_to_date = ''
stashed = '󰏖 '
modified = 'Δ${count}'
staged = '[+${count}](green)'
renamed = '󰁕 '
deleted = '󰗨 '
untracked = '?${count}'

[cmd_duration]
min_time = 2000
format = " [󱎫 $duration]($style) "
style = "yellow"

[time]
disabled = false
time_format = "%R:%S" # Format HH:MM:SS
style = "bold grey"
format = "[$time]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
